### ISSUE TITLE
someone removed Vector3d?

### ISSUE THREAD

**Issue by horatiu665** [sldsmkd/vector3d#8]
someone removed Vector3d? file is empty. went back a few commits and it's all there so maybe just an error. I also have a weird error when pulling the project, my OS (win10) changes every line in every file. that must be something with the tabs, line endings, or whatnot, idk, but I don't mind that.

**Comment by mirage3d** [comment]
It's possible that it was deleted by accident. If you check Sukenders's pull request, you can see the changes, and the part that was deleted:

https://github.com/sldsmkd/vector3d/commit/9ffe9a46fc8f843a32aecdaedff33a97051dc755

You could reconstruct the file from there.

**Comment by javiermorawski** [comment]
I'm wondering if it was an accident, or if there was a reason for the delete?

**Comment by sldsmkd** [comment]
Accident, haven't used this code in a decade. Send a PR and will merge it back in.

**Comment by sldsmkd** [comment]
Fixed
